#include "modes/ModeLexer.h"
#include "modes/LexMode.h"
#include <chrono>
#include <cctype>
namespace modes {
static void adv(const std::string&s,size_t a,size_t b,int&l,int&c){for(size_t i=a;i<b;++i)if(s[i]=='\n'){l++;c=1;}else c++;}
std::vector<ModeToken> ModeLexer::tokenizeCminus(const std::string&s,ModeStats*st)const{auto t0=std::chrono::high_resolution_clock::now();std::vector<ModeToken> o;int l=1,c=1;size_t i=0,tr=0;while(i<s.size()){if(i+1<s.size()&&s[i]=='/'&&s[i+1]=='/'){o.push_back(ModeToken{l,c,"NORMAL","COMMENT_BEGIN","//","NORMAL->LINE_COMMENT"});tr++;size_t j=s.find('\n',i);if(j==std::string::npos)j=s.size();adv(s,i,j,l,c);i=j;continue;}if(i+1<s.size()&&s[i]=='/'&&s[i+1]=='*'){o.push_back(ModeToken{l,c,"NORMAL","COMMENT_BEGIN","/*","NORMAL->BLOCK_COMMENT"});tr++;size_t j=s.find("*/",i+2);j=(j==std::string::npos)?s.size():j+2;adv(s,i,j,l,c);i=j;continue;}if(s[i]=='\"'){size_t j=i+1;while(j<s.size()&&s[j]!='\"')j++;if(j<s.size())j++;o.push_back(ModeToken{l,c,"NORMAL","STRING",s.substr(i,j-i),"NORMAL->STRING->NORMAL"});tr+=2;adv(s,i,j,l,c);i=j;continue;}if(std::isspace((unsigned char)s[i])){adv(s,i,i+1,l,c);i++;continue;}size_t j=i+1;while(j<s.size()&&!std::isspace((unsigned char)s[j])&&s[j]!='/')j++;o.push_back(ModeToken{l,c,"NORMAL","TEXT",s.substr(i,j-i),""});adv(s,i,j,l,c);i=j;}auto t1=std::chrono::high_resolution_clock::now();if(st){st->tokens=o.size();st->transitions=tr;st->elapsedUs=std::chrono::duration_cast<std::chrono::microseconds>(t1-t0).count();}return o;}
std::vector<ModeToken> ModeLexer::tokenizeTemplate(const std::string&s,ModeStats*st)const{auto t0=std::chrono::high_resolution_clock::now();std::vector<ModeToken> o;int l=1,c=1;size_t i=0,tr=0;bool text=true;while(i<s.size()){if(text){size_t j=s.find("{{",i);if(j==std::string::npos)j=s.size();if(j>i)o.push_back(ModeToken{l,c,"TEMPLATE_TEXT","TEXT",s.substr(i,j-i),""});adv(s,i,j,l,c);i=j;if(i+1<s.size()){o.push_back(ModeToken{l,c,"TEMPLATE_TEXT","OPEN_EXPR","{{","TEMPLATE_TEXT->TEMPLATE_EXPR"});adv(s,i,i+2,l,c);i+=2;text=false;tr++;}}else{size_t j=s.find("}}",i);if(j==std::string::npos)j=s.size();if(j>i)o.push_back(ModeToken{l,c,"TEMPLATE_EXPR","EXPR",s.substr(i,j-i),""});adv(s,i,j,l,c);i=j;if(i+1<s.size()){o.push_back(ModeToken{l,c,"TEMPLATE_EXPR","CLOSE_EXPR","}}","TEMPLATE_EXPR->TEMPLATE_TEXT"});adv(s,i,i+2,l,c);i+=2;text=true;tr++;}}}auto t1=std::chrono::high_resolution_clock::now();if(st){st->tokens=o.size();st->transitions=tr;st->elapsedUs=std::chrono::duration_cast<std::chrono::microseconds>(t1-t0).count();}return o;}
}
