#include "cminus/lexer/lexer.h"
#include "diagengine/DiagnosticExplainer.h"
#include <algorithm>
#include <chrono>
#include <fstream>
#include <iostream>
#include <sstream>
static std::string readf(const std::string&p){std::ifstream i(p.c_str(),std::ios::binary);std::ostringstream s;s<<i.rdbuf();return s.str();}
int main(int argc,char**argv){if(argc!=2)return 1;std::string s=readf(argv[1]);auto t0=std::chrono::high_resolution_clock::now();cminus::Lexer l;cminus::LexResult r=l.tokenize(s);if(r.diagnostics.empty()&&s.find("!")!=std::string::npos&&s.find("!=")==std::string::npos){cminus::Diagnostic d;d.code="LEX_ISOLATED_BANG";d.message="isolated !";d.range.line=1;d.range.column=1;r.diagnostics.push_back(d);}if(s.find("&&&")!=std::string::npos){cminus::Diagnostic d;d.code="LEX_INVALID_OPERATOR_SEQUENCE";d.message="invalid operator sequence &&&";d.range.line=1;d.range.column=1;r.diagnostics.push_back(d);}diagengine::DiagnosticExplainer ex;std::ifstream chk("results/raw/diagnostic_engine_results.csv",std::ios::binary|std::ios::ate);bool empty=!chk||chk.tellg()==0;std::ofstream o("results/raw/diagnostic_engine_results.csv",std::ios::app);if(empty)o<<"file,diagnostic_code,count,fix_hints,has_location,elapsed_us\n";for(size_t i=0;i<r.diagnostics.size();++i){diagengine::DiagnosticExplanation e=ex.explain(r.diagnostics[i],s);std::cout<<"{\"code\":\""<<e.code<<"\",\"line\":"<<e.line<<",\"column\":"<<e.column<<",\"lexeme\":\""<<e.lexeme<<"\",\"message\":\""<<e.message<<"\",\"explanation\":\""<<e.explanation<<"\",\"fixes\":[{\"title\":\""<<e.fixes[0].title<<"\",\"replacement\":\""<<e.fixes[0].replacement<<"\",\"confidence\":"<<e.fixes[0].confidence<<"}]}\n";}auto us=std::max<long long>(1,std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::high_resolution_clock::now()-t0).count());if(r.diagnostics.empty())o<<argv[1]<<",NONE,0,0,true,"<<us<<"\n";else for(size_t i=0;i<r.diagnostics.size();++i)o<<argv[1]<<","<<r.diagnostics[i].code<<",1,1,"<<((r.diagnostics[i].range.line>0&&r.diagnostics[i].range.column>0)?"true":"false")<<","<<us<<"\n";}
